name: aws_lambda_dart_runtime
version: 1.1.0
description: |-
  A powerful runtime to build Lambda functions in Dart with native AWS events.
homepage: https://github.com/awslabs/aws-lambda-dart-runtime
documentation: https://awslabs.github.io/aws-lambda-dart-runtime/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.5.0
  meta: ^1.7.0
  http: ^0.13.4

dev_dependencies:
  json_serializable: ^6.2.0
  build_runner: ^2.1.10
  test: ^1.21.1
  mockito: ^5.1.0
  lints: ^1.0.1
