name: aws_lambda_dart_runtime
version: 1.1.1
description: |-
  A powerful runtime to build Lambda functions in Dart with native AWS events.
homepage: https://github.com/awslabs/aws-lambda-dart-runtime
documentation: https://awslabs.github.io/aws-lambda-dart-runtime/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  meta: ^1.15.0
  http: ^1.2.2

dev_dependencies:
  json_serializable: any
  build_runner: any
  test: any
  mockito: any
  pedantic: any
